export const AFFILIATIONS = [
  { label: 'Bajoran', value: 'Bajoran' },
  { label: 'Borg', value: 'Borg' },
  { label: 'Cardassian', value: 'Cardassian' },
  { label: 'Dominion', value: 'Dominion' },
  { label: 'Federation', value: 'Federation' },
  { label: 'Ferengi', value: 'Ferengi' },
  { label: 'Hirogen', value: 'Hirogen' },
  { label: 'Kazon', value: 'Kazon' },
  { label: 'Klingon', value: 'Klingon' },
  { label: 'Non-Aligned', value: 'Non-Aligned' },
  { label: 'Romulan', value: 'Romulan' },
  { label: 'Starfleet', value: 'Starfleet' },
  { label: 'Vidiian', value: 'Vidiian' },
];

export const AFFILIATION_ABBREVIATIONS = {
  'bajoran':     '[baj]',
  'borg':        '[bor]',
  'cardassian':  '[car]',
  'dominion':    '[dom]',
  'federation':  '[fed]',
  'ferengi':     '[fer]',
  'hirogen':     '[hir]',
  'kazon':       '[kaz]',
  'klingon':     '[kli]',
  'non-aligned': '[na]',
  'romulan':     '[rom]',
  'starfleet':   '[sf]',
  'vidiian':     '[vid]',
};

export const CARD_TYPES = [
  'Dilemma',
  'Equipment',
  'Event',
  'Interrupt',
  'Mission',
  'Personnel',
  'Ship',
];

export const QUADRANTS = ['Alpha', 'Gamma', 'Delta'];

export const STAFF_OPTIONS = ['st', 'cmd'];

export const HOF_OPTIONS = ['y', 'n'];

export const UNIQUE_OPTIONS = ['y', 'n'];

export const MISSION_OPTIONS = ['p', 's', 'h'];

export const DILEMMA_TYPES = ['d', 's', 'p'];

export const ICONS = [
  'AU',
  'Cmd',
  'DS9',
  'E',
  'Fut',
  'Maq',
  'Pa',
  'Stf',
  'TN',
  'TNG',
  'TOS',
  'Voy',
];

export const KEYWORDS = [
  'Admiral',
  'Alpha',
  'Amar',
  'Artifact',
  'Assassin',
  'Assault',
  'Avenger',
  'Bajoran Resistance',
  'Bellerophon',
  'Bluegill',
  'Bortas',
  'Bozeman',
  'Cadet',
  'Capture',
  "Cha'Joh",
  'Challenger',
  'Chancellor',
  'Chef',
  'Chontay',
  'Cloaking Device',
  'Commander: Aeon',
  'Commander: Aldara',
  "Commander: Ammut'alar",
  "Commander: Audit's Spoils",
  'Commander: Aurora',
  'Commander: Aurulent',
  'Commander: Baraka',
  'Commander: Baxial',
  'Commander: Bralek',
  'Commander: Calondon',
  'Commander: Columbia',
  'Commander: Cosette',
  'Commander: Cousteau',
  'Commander: Delta Flyer',
  'Commander: Deranas',
  'Commander: Devna-Lev',
  'Commander: Devoras',
  'Commander: Ehrehin',
  'Commander: Eleventh Gradient',
  'Commander: Enterprise',
  'Commander: Fantine',
  'Commander: Fortune',
  'Commander: Future Enterprise',
  "Commander: Gal Gath'thong",
  'Commander: Goraxus',
  'Commander: Groumall',
  'Commander: Guingouin',
  'Commander: Haakona',
  'Commander: Hard Bargain',
  "Commander: Izir'isel",
  'Commander: Javert',
  'Commander: Jovis',
  'Commander: Khazara',
  'Commander: Kitara',
  'Commander: Kraxon',
  'Commander: Krayton',
  'Commander: Kreechta',
  'Commander: Kronos One',
  'Commander: Kumari',
  'Commander: Kurdon',
  "Commander: Kyana's Hope",
  "Commander: Li'seria",
  "Commander: Locutus' Borg Cube",
  'Commander: Memenda',
  'Commander: Mondor',
  'Commander: NX-Prototype',
  'Commander: Nammoch',
  'Commander: Naprem',
  'Commander: Niala',
  'Commander: Olarra',
  'Commander: Phoenix',
  'Commander: Prakesh',
  "Commander: Quark's Treasure",
  "Commander: Queen's Borg Cube",
  'Commander: Quetsivoo',
  'Commander: Redemption',
  'Commander: Regency 1',
  'Commander: Reklar',
  'Commander: Rokassa',
  'Commander: Rovaran',
  'Commander: Salvaged Attack Ship',
  'Commander: Scimitar',
  'Commander: Serrola',
  'Commander: Solace',
  'Commander: Soterus',
  'Commander: Sphere 117',
  'Commander: Starship Defiant',
  'Commander: Starship Excelsior',
  'Commander: Talnot',
  'Commander: Tama',
  "Commander: Tenak'talar",
  'Commander: Terix',
  'Commander: Think Tank Ship',
  'Commander: Trager',
  'Commander: Trolarak',
  'Commander: Trullux',
  'Commander: Tykk',
  'Commander: Valdore',
  'Commander: Valjean',
  'Commander: Vetar',
  'Commander: Xhosa',
  'Commodity',
  'Constellation',
  'Consume: 1',
  'Consume: 2',
  'Consume: 3',
  'Consume: X',
  'Crime',
  'Dabo Girl',
  'Decay: 2',
  'Decay: 3',
  'Decay: 4',
  'Decay: 5',
  'Defiant',
  'Dissident',
  'Drone',
  'Enterprise',
  'Enterprise-A',
  'Enterprise-B',
  'Enterprise-C',
  'Enterprise-D',
  'Enterprise-E',
  'Equinox',
  'Exeter',
  'Founder',
  'Gatherer',
  'General',
  'Genetically Enhanced',
  'Glinn',
  'Gul',
  'Hand Weapon',
  'Harbinger',
  "Hegh'ta",
  'High Council Member',
  'Holoprogram',
  'Horizon',
  'Host',
  'Infiltration',
  'Infiltrator',
  'Interlink: Anthropology',
  'Interlink: Archaeology',
  'Interlink: Astrometrics',
  'Interlink: Biology',
  'Interlink: Exobiology',
  'Interlink: Geology',
  'Interlink: Navigation',
  'Interlink: Physics',
  'Interlink: Programming',
  'Interlink: Transporters',
  'Interlink: a skill on your non-[Bor] personnel present',
  'Kai',
  "Kla'Diyus",
  'Lakota',
  'Legate',
  'Lukara',
  'MACO',
  "Maht-H'a",
  'Maneuver',
  'Mirror',
  'Morph',
  'Nebula',
  "Negh'Var",
  "Ning'tao",
  'Nucleogenic',
  'Odyssey',
  'Orb',
  'Pagh',
  'Pah-wraith',
  'Paranoia',
  'Pasteur',
  'Persistent',
  'Phoenix',
  'Praetor',
  'Prometheus',
  'Prophet',
  'Prylar',
  'Punishment',
  'Pursuit',
  'Qam-Chee',
  "Qel'Poh",
  'Recall: 1',
  'Recall: 2',
  'Region: Arkaria System',
  'Region: Badlands',
  'Region: Bajor System',
  'Region: Borderland',
  'Region: Briar Patch',
  'Region: Cardassia System',
  'Region: Delphic Expanse',
  'Region: Demilitarized Zone',
  'Region: Great Barrier',
  'Region: Ligos System',
  'Region: Nekrit Expanse',
  'Region: Neutral Zone',
  'Region: Omarion Nebula',
  'Region: Omicron Theta System',
  'Region: Orias System',
  "Region: Qo'noS System",
  'Region: Rakhari Sector',
  'Region: Romulus System',
  'Region: Sector 001',
  'Region: Sector 500',
  'Region: Stakoron System',
  'Region: The Void',
  'Region: Varria System',
  'Relativity',
  'Reliant',
  'Replicate - Discard a Thief personnel from hand',
  'Replicate - Discard a [Bor] card from hand',
  'Replicate - Discard a [Maq] personnel from hand',
  'Replicate - Discard a card from hand',
  'Replicate - Discard an event from your hand',
  'Replicate - Discard the top card of your deck',
  'Replicate - Discard two cards from hand',
  "Replicate - Kill your Jem'Hadar",
  "Replicate - Place the top card of your dilemma pile face up beneath an opponent's incomplete non-headquarters mission",
  'Replicate - Spend two counters',
  'Ritual',
  'Rotarran',
  'Rule',
  'Senator',
  'Shape-shifter',
  'Smuggler',
  'Species 8472',
  'Stargazer',
  'Sutherland',
  "T'Kumbra",
  "T'Ong",
  'Temporal',
  'Thief',
  'Think Tank',
  'Tsunkatse',
  'Valiant',
  'Vedek',
  "Voq'leng",
  'Vorn',
  'Voyager',
  'Waiter',
  'Yamato',
];

export const SKILLS = [
  'Acquisition',
  'Anthropology',
  'Archaeology',
  'Astrometrics',
  'Biology',
  'Diplomacy',
  'Engineer',
  'Exobiology',
  'Geology',
  'Honor',
  'Intelligence',
  'Law',
  'Leadership',
  'Medical',
  'Navigation',
  'Officer',
  'Physics',
  'Programming',
  'Science',
  'Security',
  'Telepathy',
  'Transporters',
  'Treachery',
]

export function missionRequirements(card) {
  const count = {};
  console.log("unparsed: " + card.name + " requirements is: " + card.skills);
  card.skills.split(',').forEach((token) => {
    var match = /(\d?)\s(\S+)/.exec(token);
    if (match !== null) {
      if (SKILLS.includes(match[2])) {
        count[match[2]] = (count[match[2]] || 0) + (match[1] || 1);
      }
    }
  });
  console.log("parsed: " + card.name + " requirements is: ");
  console.log(count);
  return count;
}
