export const SETS: { label: string; value: string }[] = [
  { label: 'Where No One Has Gone Before', value: 'WNOHGB' },
  { label: 'Realm of Fear', value: 'RoF' },
  { label: 'Finding Our Way', value: 'FOW' },
  { label: 'Phage', value: 'Ph' },
  { label: 'Continuing Mission', value: 'CM' },
  { label: 'Second Chances', value: 'SC' },
  { label: 'Timeless', value: 'Tl' },
  { label: 'Second Skin', value: 'SS' },
  { label: 'The Menagerie', value: 'TM' },
  { label: 'Classification: Civilian', value: 'CC' },
  { label: 'Caretaker', value: 'Ctkr' },
  { label: 'Heroes and Demons', value: 'HaD' },
  { label: 'Shore Leave', value: 'SL' },
  { label: 'Move Along Home', value: 'MAH' },
  { label: 'Apocalypse Rising', value: 'AR' },
  { label: 'All Our Yesterdays', value: 'AoY' },
  { label: 'The Omega Directive', value: 'OD' },
  { label: 'Inheritance', value: 'In' },
  { label: 'Borderless Promos', value: 'BP' },
  { label: 'Sacrifice of Angels', value: 'SOA' },
  { label: 'A Less Perfect Union', value: 'ALPU' },
  { label: 'Qpid', value: 'QP' },
  { label: 'Shattered Mirror', value: 'SM' },
  { label: 'Warp Pack: Access Denied', value: 'WPAD' },
  { label: 'Far Beyond the Stars', value: 'FBtS' },
  { label: 'Symbiosis', value: 'Sym' },
  { label: 'Dead Stop', value: 'DS' },
  { label: 'The Nth Degree', value: 'ND' },
  { label: 'Zero Hour', value: 'ZH' },
  { label: 'Star Trek 50', value: '50' },
  { label: 'Hard Time', value: 'HT' },
  { label: 'Infinite Diversity Remastered', value: 'IDR' },
  { label: 'A Time to Stand', value: 'ATtS' },
  { label: 'Face of the Enemy', value: 'FotE' },
  { label: 'Lower Decks', value: 'LD' },
  { label: 'Strange Bedfellows', value: 'SB' },
  { label: '20th Anniversary Collection', value: 'AC' },
  { label: 'Balance of Terror', value: 'BoT' },
  { label: 'Return to Grace', value: 'RtG' },
  { label: 'Unnatural Selection', value: 'US' },
  { label: 'Matter of Time', value: 'MoT' },
  { label: 'Tapestry', value: 'Tapestry' },
  { label: 'Lineage', value: 'Lineage' },
  { label: 'Unity', value: 'Unity' },
  { label: 'Tacking Into the Wind', value: 'TITW' },
  { label: 'Extreme Measures', value: 'EM' },
  { label: 'Peak Performance', value: 'PP' },
  { label: 'Infinite Diversity', value: 'ID' },
  { label: 'Allegiance', value: 'Alg' },
  { label: 'Legacy', value: 'Leg' },
  { label: 'This Side of Paradise', value: 'TSOP' },
  { label: 'Raise the Stakes', value: 'RTS' },
  { label: 'Virtual Archive Portrait', value: 'VAP' },
  { label: 'Favor the Bold', value: 'FTB' },
  { label: 'The Undiscovered Country', value: 'TUC' },
  { label: 'Virtual Promo Cards', value: 'VP' },
  { label: 'What You Leave Behind', value: 'WYLB' },
  { label: 'In a Mirror Darkly', value: 'IMD' },
  { label: 'These Are the Voyages', value: 'TV' },
  { label: 'Genesis', value: 'Ge' },
  { label: "Captain's Log", value: 'CL' },
  { label: 'Dangerous Missions', value: 'DM' },
  { label: 'Adversaries Collection', value: 'AdC' },
  { label: 'To Boldly Go', value: 'BG' },
  { label: 'Strange New Worlds', value: 'SW' },
  { label: 'Archive Portrait', value: 'AP' },
  { label: 'Reflections 2.0', value: 'R2' },
  { label: 'Fractured Time', value: 'FT' },
  { label: 'Tenth Anniversary Collection', value: 'X' },
  { label: 'Necessary Evil', value: 'NE' },
  { label: 'Call to Arms', value: 'CA' },
  { label: 'Energize', value: 'En' },
  { label: 'Second Edition', value: 'SE' },
  { label: 'Starter Reprints', value: 'SR' },
  { label: 'Promo Cards', value: 'Promo' },
];

export const SET_ABBREVIATIONS_TO_NAMES: Record<string, string> = Object.fromEntries(
  SETS.map(({ label, value }) => [value.toLowerCase(), label])
);

export const AFFILIATIONS: { label: string; value: string }[] = [
  { label: 'Bajoran', value: 'Bajoran' },
  { label: 'Borg', value: 'Borg' },
  { label: 'Cardassian', value: 'Cardassian' },
  { label: 'Dominion', value: 'Dominion' },
  { label: 'Federation', value: 'Federation' },
  { label: 'Ferengi', value: 'Ferengi' },
  { label: 'Klingon', value: 'Klingon' },
  { label: 'Non-Aligned', value: 'Non-Aligned' },
  { label: 'Romulan', value: 'Romulan' },
  { label: 'Starfleet', value: 'Starfleet' },
  { label: 'Vidiian', value: 'Vidiian' },
];

export const AFFILIATION_ABBREVIATIONS: Record<string, string> = {
  'bajoran':     '[baj]',
  'borg':        '[bor]',
  'cardassian':  '[car]',
  'dominion':    '[dom]',
  'federation':  '[fed]',
  'ferengi':     '[fer]',
  'klingon':     '[kli]',
  'non-aligned': '[na]',
  'romulan':     '[rom]',
  'starfleet':   '[sf]',
  'vidiian':     '[vid]',
};

export const CARD_TYPES: string[] = [
  'Dilemma',
  'Equipment',
  'Event',
  'Interrupt',
  'Mission',
  'Personnel',
  'Ship',
];

export const QUADRANTS: string[] = ['Alpha', 'Gamma', 'Delta'];

export const STAFF_OPTIONS: string[] = ['st', 'cmd'];

export const HOF_OPTIONS: string[] = ['y', 'n'];

export const UNIQUE_OPTIONS: string[] = ['y', 'n'];

export const MISSION_OPTIONS: string[] = ['p', 's', 'h'];

export const DILEMMA_TYPES: string[] = ['d', 's', 'p'];

export const AFFILIATION_ICONS: Record<string, string> = {
  'bajoran': '/icons/icon_affiliation_bajoran.gif',
  'borg': '/icons/icon_affiliation_borg.gif',
  'cardassian': '/icons/icon_affiliation_cardassian.gif',
  'dominion': '/icons/icon_affiliation_dominion.gif',
  'federation': '/icons/icon_affiliation_federation.gif',
  'ferengi': '/icons/icon_ferengi.gif',
  'klingon': '/icons/icon_affiliation_klingon.gif',
  'non-aligned': '/icons/icon_nonaligned.gif',
  'romulan': '/icons/icon_affiliation_romulan.gif',
  'starfleet': '/icons/icon_affiliation_starfleet.gif',
  'vidiian': '/icons/icons_affiliation_vidiian.png',
};

export const CARD_ICON_IMAGES: Record<string, string | null> = {
  'au': '/icons/icon_au.gif',
  'cmd': '/icons/icon_command.gif',
  'ds9': '/icons/icon_ds9.gif',
  'e': '/icons/icon_earth.gif',
  'fut': '/icons/icon_future.gif',
  'maq': '/icons/icon_maquis.gif',
  'pa': '/icons/icon_past.gif',
  'stf': '/icons/icon_staff.gif',
  'tn': '/icons/icon_teroknor.gif',
  'tng': '/icons/icon_tng.gif',
  'tos': '/icons/icon_tos.gif',
  'voy': '/icons/icon_voyager.gif',
};

export const DILEMMA_TYPE_ICONS: Record<string, string | null> = {
  'd': '/icons/icon_dual.gif',
  's': '/icons/icon_space.gif',
  'p': '/icons/icon_planet.gif',
};

export const MISSION_TYPE_ICONS: Record<string, string | null> = {
  'p': '/icons/icon_planet.gif',
  's': '/icons/icon_space.gif',
  'h': '/icons/icon_headquarters.gif',
};

export const ICONS: string[] = [
  'AU',
  'Cmd',
  'DS9',
  'E',
  'Fut',
  'Maq',
  'Pa',
  'Stf',
  'TN',
  'TNG',
  'TOS',
  'Voy',
];

export const KEYWORDS: string[] = [
  'Admiral',
  'Alpha',
  'Artifact',
  'Assassin',
  'Assault',
  'Bajoran Resistance',
  'Bluegill',
  'Cadet',
  'Capture',
  'Chancellor',
  'Chef',
  'Cloaking Device',
  'Commander',
  'Commodity',
  'Consume',
  'Crime',
  'Dabo Girl',
  'Decay',
  'Dissident',
  'Drone',
  'Founder',
  'Gatherer',
  'General',
  'Genetically Enhanced',
  'Glinn',
  'Gul',
  'Hand Weapon',
  'Harbinger',
  'High Council Member',
  'Holoprogram',
  'Host',
  'Infiltration',
  'Infiltrator',
  'Interlink',
  'Kai',
  'Legate',
  'MACO',
  'Maneuver',
  'Mirror',
  'Morph',
  'Nebula',
  'Nucleogenic',
  'Orb',
  'Pah-wraith',
  'Paranoia',
  'Persistent',
  'Praetor',
  'Prophet',
  'Prylar',
  'Punishment',
  'Pursuit',
  'Q',
  'Recall',
  'Region: Arkaria System',
  'Region: Badlands',
  'Region: Bajor System',
  'Region: Borderland',
  'Region: Briar Patch',
  'Region: Cardassia System',
  'Region: Delphic Expanse',
  'Region: Demilitarized Zone',
  'Region: Great Barrier',
  'Region: Ligos System',
  'Region: Nekrit Expanse',
  'Region: Neutral Zone',
  'Region: Omarion Nebula',
  'Region: Omicron Theta System',
  'Region: Orias System',
  "Region: Qo'noS System",
  'Region: Rakhari Sector',
  'Region: Romulus System',
  'Region: Sector 001',
  'Region: Sector 500',
  'Region: Stakoron System',
  'Region: The Void',
  'Region: Varria System',
  'Replicate',
  'Ritual',
  'Rule',
  'Senator',
  'Shape-shifter',
  'Smuggler',
  'Species 8472',
  'Temporal',
  'Thief',
  'Think Tank',
  'Tsunkatse',
  'Vedek',
  'Waiter',
];

export const SKILLS: string[] = [
  'Acquisition',
  'Anthropology',
  'Archaeology',
  'Astrometrics',
  'Biology',
  'Diplomacy',
  'Engineer',
  'Exobiology',
  'Geology',
  'Honor',
  'Intelligence',
  'Law',
  'Leadership',
  'Medical',
  'Navigation',
  'Officer',
  'Physics',
  'Programming',
  'Science',
  'Security',
  'Telepathy',
  'Transporters',
  'Treachery',
]

// AUTO-GENERATED by scripts/extract_card_options.sh — do not edit manually
export const SHIP_CLASSES: string[] = [
  "A'norum Class",
  'Akira Class',
  'Ambassador Class',
  'Antares Class',
  'Assimilator Class',
  'Attack Ship',
  "B'rel Class",
  'Battleship',
  'Bestri Class',
  'Bird-of-Prey Class',
  'Breen Warship Class',
  'Brendob Class',
  'Centaur Class',
  'Class J Cargo Ship',
  'Combat Class',
  'Condor Class',
  'Constellation Class',
  'Constitution Class',
  'Cruiser Class',
  'Cube',
  "D'Deridex Class",
  "D'Kora Class",
  "D'deridex Class",
  'D-12 Class',
  'D-7 Class',
  'Danube Class',
  'Darmok Class',
  'Dauntless Class',
  'Defiant Class',
  'Delta Flyer Class',
  'Diamond',
  'Drexia Class',
  'Excelsior Class',
  'Freighter Class',
  'Galaxy Class',
  'Galor Class',
  "Guzah'far Class",
  'Hope Class',
  'Husnock Class',
  'Interceptor Class',
  'Intrepid Class',
  'J Class',
  'Janitza Class',
  "K'Vort Class",
  "K't'inga Class",
  'Keldon Class',
  'Kressari Freighter Class',
  'Kumari Class',
  'Kyana Class',
  'Lanora Class',
  'Ma-Karn Class',
  'Maraar Class',
  'Military Freighter',
  'Miranda Class',
  'NX Class',
  "Na'Far Class",
  'Nebula Class',
  "Negh'Var Class",
  'Nimaria Class',
  'Norexan Class',
  'Nova Class',
  'Oberth Class',
  'Ornathia Class',
  'Perikian Class',
  'Phoenix Class',
  'Prometheus Class',
  'Scimitar Class',
  'Shabren Class',
  'Shuttle',
  'Sovereign Class',
  'Soyuz Class',
  'Sphere',
  'Transport Class',
  'Type-8 Shuttlecraft',
  'Type-9 Shuttlecraft',
  'Unknown Class',
  'Vinum Class',
  'Virayllan Class',
  "Vor'cha Class",
  'Warship',
  'Wells Class',
  'Yacht',
  'Zibalian Class',
];

export const SPECIES: string[] = [
  'Acamarian',
  'Aenar',
  'Alien',
  'Alien/Human',
  'Alien/Human/Ikaaran',
  'Andorian',
  'Android',
  'Android/Borg',
  'Angosian',
  'Antican',
  'Atrean',
  "Ba'ku",
  'Bajoran',
  'Bajoran/Cardassian',
  'Bandi',
  'Barzan',
  'Beast',
  'Benzite',
  'Betazoid',
  'Betazoid/Human',
  'Bioplasmic Lifeform',
  'Bolian',
  'Borg',
  'Boslic',
  'Breen',
  'Brekkian',
  'Bynar',
  'Cairn',
  'Caitian',
  'Caldonian',
  'Cardassian',
  'Chameloid',
  'Changeling',
  'Deltan',
  'Denobulan',
  'Dosi',
  'El-Aurian',
  'Elaysian',
  'Farian',
  'Ferengi',
  'Flaxian',
  'Gorn',
  'Grazerite',
  'Hekaran',
  'Hirogen',
  'Hologram',
  'Human',
  'Human/Alien',
  'Human/Klingon',
  'Human/Ktarian',
  'Human/Napean',
  'Human/Romulan',
  'Human/Trill',
  'Human/Vulcan',
  'Hupyrian',
  'Idanian',
  "Jem'Hadar",
  'Kaelon',
  'Karemma',
  'Kellerun',
  'Klaestron',
  'Klingon',
  'Klingon/Romulan',
  'Kobali',
  'Kobliad',
  'Kreetassan',
  'Krenim',
  'Kressari',
  'Kriosian',
  'Ktarian',
  'Kzinti',
  'Lethean',
  'Lurian',
  'Malon',
  'Mari',
  'Markalian',
  'Mechanoid',
  'Minaran',
  'Miradorn',
  "Na'kuhl",
  'Nausicaan',
  'Norcadian',
  'Nyrian',
  'Ocampa',
  'Ochshea',
  'Orion',
  'Ornaran',
  'Pakled',
  'Pendari',
  'Rakhari',
  'Ramatin',
  'Reman',
  'Risan',
  'Romulan',
  'Satarran',
  'Selay',
  'Simbiot',
  'Solari',
  "Son'a",
  'Suliban',
  "T'Lani",
  'Takaran',
  'Talaxian',
  'Talaxian/Vulcan',
  'Talemstran',
  'Tamarian',
  'Tanugan',
  'Tellarite',
  'Tiburonian',
  'Tosk',
  'Triannon',
  'Trill',
  'Ullian',
  'Ventaxian',
  'Vidiian',
  'Vorgon',
  'Vorta',
  'Vulcan',
  'Wadi',
  'Yridian',
  'Zakdorn',
  'Zalkonian',
  'Zibalian',
];

// END AUTO-GENERATED

export function missionRequirements(card: { name: string; skills: string }): Record<string, number> {
  const count: Record<string, number> = {};
  console.log("unparsed: " + card.name + " requirements is: " + card.skills);
  card.skills.split(',').forEach((token) => {
    var match = /(\d?)\s(\S+)/.exec(token);
    if (match !== null) {
      if (SKILLS.includes(match[2])) {
        count[match[2]] = (count[match[2]] || 0) + (match[1] ? parseInt(match[1]) : 1);
      }
    }
  });
  console.log("parsed: " + card.name + " requirements is: ");
  console.log(count);
  return count;
}
