#!/usr/bin/env bash
# extract_card_options.sh
#
# Extracts unique Class and Species values from the card data TSV and
# writes/overwrites the SHIP_CLASSES and SPECIES constant blocks in
# src/lib/missionRequirements.ts between sentinel comments.
#
# Usage: bash scripts/extract_card_options.sh
# Run this script whenever public/cards_with_processed_columns.txt is updated.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TSV="$REPO_ROOT/public/cards_with_processed_columns.txt"
TARGET="$REPO_ROOT/src/lib/missionRequirements.ts"

if [[ ! -f "$TSV" ]]; then
  echo "Error: card data file not found at $TSV" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Extract unique values using Node.js (already required by the project).
# ---------------------------------------------------------------------------
EXTRACTED=$(node -e "
const fs = require('fs');
const lines = fs.readFileSync('$TSV', 'utf8').split('\n');
const headers = lines[0].split('\t');
const classIdx = headers.indexOf('Class');
const speciesIdx = headers.indexOf('Species');

const classes = new Set();
const species = new Set();

for (let i = 1; i < lines.length; i++) {
  const cols = lines[i].split('\t');
  const c = (cols[classIdx] || '').replace(/^\"|\"$/g, '').trim();
  const s = (cols[speciesIdx] || '').replace(/^\"|\"$/g, '').trim();
  if (c) classes.add(c);
  if (s) species.add(s);
}

process.stdout.write(JSON.stringify({
  classes: [...classes].sort(),
  species: [...species].sort(),
}));
")

# Parse extracted JSON values
CLASSES=$(node -e "const d=JSON.parse(process.argv[1]); process.stdout.write(JSON.stringify(d.classes));" "$EXTRACTED")
SPECIES_LIST=$(node -e "const d=JSON.parse(process.argv[1]); process.stdout.write(JSON.stringify(d.species));" "$EXTRACTED")

# ---------------------------------------------------------------------------
# Build the replacement block using Node.js for reliable string handling.
# ---------------------------------------------------------------------------
node -e "
const fs = require('fs');
const classes = $CLASSES;
const speciesList = $SPECIES_LIST;

const indent = '  ';

const classLines = classes.map(c => {
  const escaped = c.includes(\"'\") ? '\"' + c + '\"' : \"'\" + c + \"'\";
  return indent + escaped + ',';
}).join('\n');

const speciesLines = speciesList.map(s => {
  const escaped = s.includes(\"'\") ? '\"' + s + '\"' : \"'\" + s + \"'\";
  return indent + escaped + ',';
}).join('\n');

const block = \`// AUTO-GENERATED by scripts/extract_card_options.sh — do not edit manually
export const SHIP_CLASSES: string[] = [
\${classLines}
];

export const SPECIES: string[] = [
\${speciesLines}
];
// END AUTO-GENERATED\`;

const target = '$TARGET';
let content = fs.readFileSync(target, 'utf8');
const start = content.indexOf('// AUTO-GENERATED by scripts/extract_card_options.sh');
const end = content.indexOf('// END AUTO-GENERATED');
if (start === -1 || end === -1) {
  console.error('Sentinel comments not found in ' + target);
  process.exit(1);
}
const endFull = end + '// END AUTO-GENERATED'.length;
const newContent = content.slice(0, start) + block + content.slice(endFull);
fs.writeFileSync(target, newContent, 'utf8');
console.log('Updated ' + target);
"

echo "Done. SHIP_CLASSES and SPECIES updated in $TARGET"
